### ISSUE TITLE
Creating app fails on first run

### ISSUE THREAD

**Issue by B0bby31** [hugojosefson/proxmox-create-docker-ct#2]
Hello, was interested to try out your project! I downloaded the script and on running I encountered the following error:

error: Uncaught (in promise) Error: Command failed with exit code 255: ["pveam","download","local","alpine-3.17-default_20221129_amd64.tar.xz"]
    throw new CommandFailureError(output, cmd);
          ^
    at tryRun (https://deno.land/x/run_simple@2.1.0/src/run.ts:104:11)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async run (https://deno.land/x/run_simple@2.1.0/src/run.ts:127:12)
    at async ensureExistsTemplate (file:///usr/local/bin/create-docker-ct-files/ct-template.ts:191:3)
    at async createCtTemplate (file:///usr/local/bin/create-docker-ct-files/ct-template.ts:69:28)
    at async ensureExistsCtTemplate (file:///usr/local/bin/create-docker-ct-files/ct-template.ts:180:12)
    at async file:///usr/local/bin/create-docker-ct-files/cli.ts:60:28
    
I checked my proxmox installation and it seems to only offer a 3.18 alpine template. Maybe it is an idea to start supporting 3.18? Also, it would be nice if you notify the users of this potentially happening (if they were to choose one of the non-default images). To get around it (for the time being), I am using the ubuntu image.

After resolving this issue, I ran into another:

? Pick storage for appdata for CT ngm. › SpeedData  zfspool  active  458689904    6378172     452311732   1.39%
error: Uncaught (in promise) Error: Could not find path for storage SpeedData.
    throw new Error(`Could not find path for storage ${storage.name}.`);
          ^
    at getAppdataDir (file:///usr/local/bin/create-docker-ct-files/ct-template.ts:31:11)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async createCt (file:///usr/local/bin/create-docker-ct-files/ct-template.ts:158:22)
    at async file:///usr/local/bin/create-docker-ct-files/cli.ts:76:30
    
I believe this is due to me using a zfs pool. For one, the pvesh output for my storage array only gives a mountpoint (not a path). Even after fixing this, you would run into the issue that the appdata dir should be created using the zfs tool and not mkdir ( i think ).

**Comment by hugojosefson** [comment]
Thank you for the report!

I have updated the program to support alpine 3.18, and removed older versions that are not available for download.

Please try again, and let me know if you still get the second problem!

**Comment by B0bby31** [comment]
Hi, although your changes fixed the first error I encountered (it now succesfully created the alpine template), it still gets stuck when making the actual container (with the same error as before):

? Pick storage for appdata for CT ngm. › SpeedData  zfspool  active  458692028    42535788    416156240   9.27%
error: Uncaught (in promise) Error: Could not find path for storage SpeedData.
    throw new Error(`Could not find path for storage ${storage.name}.`);
          ^
    at getAppdataDir (file:///usr/local/bin/create-docker-ct-files/ct-template.ts:31:11)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async createCt (file:///usr/local/bin/create-docker-ct-files/ct-template.ts:158:22)
    at async file:///usr/local/bin/create-docker-ct-files/cli.ts:75:30

**Comment by hugojosefson** [comment]
Thank you @B0bby31 for your patience!

I have had an opportunity to look into this just now, and found that different types of storage use different keys in the API for where they are mounted. The `dir` and `nfs` type have their directory path in a property named `path`, while `zfspool` has it in `mountpoint`.

Now I support both, and have tested it with both, which works. Please try again! :)
